apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/veerbal1/homestead:b5daf53
          env:
            - name: DATABASE_URL
              value: postgres://homestead:devpass@host.docker.internal:5433/homestead?sslmode=disable
            - name: API_KEY
              value: s3cr3t-key-abc
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
